import type { Product } from './types/product';

export const sampleProducts: Product[] = [
  {
    name: 'Nice Slim Pant',
    slug: 'nice-slim-pant',
    category: 'Pants',
    image: '/images/nice-pant.jpg',
    price: 200,
    countInStock: 378,
    brand: 'Nike',
    rating: 4.2,
    numReviews: 200,
    description: 'High Quality product',
  },
  {
    name: 'Nice Shirt',
    slug: 'nice-shirt',
    category: 'Shirts',
    image: '/images/nice-shirt.jpg',
    price: 120,
    countInStock: 400,
    brand: 'Nike',
    rating: 4.5,
    numReviews: 10,
    description: 'A popular shirt',
  },
  {
    name: 'Adidas Shirt',
    slug: 'adidas-shirt',
    category: 'Shirts',
    image: '/images/adidas-shirt.jpg',
    price: 100,
    countInStock: 250,
    brand: 'Adidas',
    rating: 4.0,
    numReviews: 10,
    description: 'High Quality product',
  },

  {
    name: 'LG Watch',
    slug: 'lg-watch',
    category: 'Watches',
    image: '/images/lg-watch.jpg',
    price: 180,
    countInStock: 400,
    brand: 'LG',
    rating: 4.5,
    numReviews: 10,
    description: 'Most Demanded Watch',
  },
]
